### ISSUE TITLE
Wow this is awesome

### ISSUE THREAD

**Issue by ankitrgadiya** [kbrsh/throw#5]

**Comment by kbrsh** [comment]
Thanks! @ankitrgadiya :smile:

**Comment by ankitrgadiya** [comment]
Can I use it for myself I mean by forking it and tweaking the url, and I also wanna use snipit to shorten the urls.

**Comment by kbrsh** [comment]
Sure! As long as you link back to Throw somewhere, it can be small text in the top. 

Super glad you like Throw and Snip! :+1:

**Comment by ankitrgadiya** [comment]
Yeah I'll keep it all the same All that Throw Made by Kabir and that Octrocat I'll just use my own domain.
You definately deserve the credit.

**Comment by kbrsh** [comment]
Then sure! @ankitrgadiya
