### ISSUE TITLE
Domain Expired

### ISSUE THREAD

**Issue by goknsh** [kbrsh/throw#6]
throw.ga has expired...
renew ASAP

**Comment by goknsh** [comment]
don't know why CNAME was deleted

**Comment by goknsh** [comment]
doesn't work with github pages btw...

**Comment by goknsh** [comment]
i see you changed it now

**Comment by kbrsh** [comment]
Just updated it @akaanksh.
Should be working on [this domain](https://kbrsh.github.io/throw).
